---
- hosts: all
  become: yes
  tasks:
    - name: update and upgrade apt packages
      apt: update_cache=yes upgrade=dist
    - name: install software
      apt: name={{ item }} state=present
      with_items:
        - compizconfig-settings-manager
        - firefox
        - fonts-dejavu
        - fonts-inconsolata
        - gconf2
        - git
        - git-flow
        - git-flow
        - gitk
        - guake
        - jq
        - pidgin
        - pidgin-otr
        - python-pip
        - python2.7-dev
        - python3.4-dev
        - ruby
        - ruby-dev
        - systemd-sysv
        - ubuntu-standard
        - zlib1g-dev
        - zsh
- hosts: all
  tasks:
    - name: install homesick
      gem: name=homesick state=latest
    - name: clone storaxcastle
      command: homesick clone storax/storaxcastle
      args:
        creates: /home/vagrant/.homesick/repos/storaxcastle
    - name: link storaxcastle
      command: homesick symlink stroaxcastle
- host: all
  tasks:
    - name: Set homeshell to zsh
      become: yes
      command: chsh -s `which zsh` vagrant
    - name: Download antigen
      get-url:
        args:
          url: https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh
          dest: /home/vagrant/antigen.zsh
- host: all
  become: yes
  vars:
    emacsver: emacs-24.5
    emacsdir: /home/vagrant/emacs-src/
  tasks:
    - name: check if emacs is installed
      command: dpkg-query -l emacs
      register: emacs_installed
      failed_when: emacs_installed.rc > 1
      changed_when: no
    - name: install python emacs packages
      pip: name={{ item }} state=present
      with_items:
        - elpy
        - pyflakes
    - name: download emacs source
      get-url:
        args:
          url: http://ftpmirror.gnu.org/emacs/{{ emacsver }}.tar.gz
          dest: {{ emacsdir }}{{ emacsver}}.tar.gz
    - name: unzip emacs source
      unarchive:
        args:
          src: {{ emacsdir }}{{ emacsver}}.tar.gz
          dest: {{ emacsdir }}{{ emacsver}} copy=no
          creates: {{ emacsdir }}{{ emacsver }}
    - name: copy dbconf selections file
      copy: src=dbconf-selections dest=/tmp/dbconf-selections
    - name: set dbconf selections
      command: dbconf-set-selections /tmp/dbconf-selections
    - name: install emacs build dependencies
      apt: name=emacs24 state=build-dep
    - name: configure emacs
      command: ./configure
        args:
          chdir: {{ emacsdir }}{{ emacsver }}
          creates: {{ emacsdir }}{{ emacsver }}/config.status
    - name: make emacs
      command: make
        args:
          chdir: {{ emacsdir }}{{ emacsver}}
          creates: {{ emacsdir }}{{ emacsver }}/src/emacs
    - name: install checkinstall
      apt: name=checkinstall state=present
    - name: execute checkinstall
      command: checkinstall -y chdir={{ emacsdir }}{{ emacsver}}
      when: emacs_installed.rc == 1

      /home/vagrant/emacs-src/emacs2/emacs-24.5/lisp/progmodes/cc-mode.elc
